services:
  kbms:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # - ./app:/app/app
      # - ./tests:/app/tests
      - .:/app
    command: ["uvicorn", "app.main:app", "--host=0.0.0.0", "--port=8000", "--reload", "--access-log"]
